# Generated by Django 4.1 on 2022-10-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='alamat_rumah',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='tanggal_lahir',
        ),
    ]
