# Generated by Django 4.1 on 2022-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=200)),
                ('judul_penelitian', models.CharField(max_length=200)),
                ('nama_ketua_tim', models.CharField(max_length=200, null=True)),
                ('kepakaran_ketua_tim', models.CharField(max_length=200)),
                ('nama_dan_identitas_dosen_anggota_penelitian', models.CharField(max_length=200)),
                ('nama_dan_identitas_mahasiswa_yang_dilibatkan', models.CharField(max_length=200)),
            ],
        ),
    ]
